import type { Metadata } from 'next'
import '../globals.css'
import Nav from '@/components/others/Nav'
import Link from 'next/link'
import MobileHeader from '@/components/others/MobileHeader'

export const metadata: Metadata = {
  title: 'GYLOG',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='bg-dark-1 flex flex-col items-center'>
      <header className='bg-dark-1 w-full h-16 flex justify-center fixed bottom-0 sm:static'>
        <Nav />
        <Link href='/' className='text-green-700 hover:text-green-500 text-3xl font-bold fixed top-4 left-4 hidden sm:block'>GYLOG</Link>
      </header>

      <MobileHeader />

      {children}
    </div>
  )
}
