import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Nav from '@/components/others/Nav'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GYLOG',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-dark-1`}>
        <header className='w-full h-16 flex justify-center fixed bottom-0 sm:static'>
          <Nav />
          <Link href='/' className='text-green-700 hover:text-green-500 text-3xl font-bold absolute top-4 left-4 hidden sm:block'>GYLOG</Link>
        </header>
        {children}
      </body>
    </html>
  )
}
